Team.destroy_all
Player.destroy_all

connor = Player.create!(name: "Connor McDavid", age: 20, position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8478402.jpg")
sidney = Player.create!(name: "Sidney Crosby", age: 29 , position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8471675.jpg")
patrick = Player.create!(name: "Patrick Kane", age: 28 , position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8474141.jpg")
nicklas= Player.create!(name: "Nicklas Backstrom", age: 29 , position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8473563.jpg")
nikita= Player.create!(name: "Nikita Kucherov", age: 23 , position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8476453.jpg")
brad= Player.create!(name: "Brad Marchand", age: 28 , position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8473419.jpg")
mark= Player.create!(name: "Mark Scheifele", age: 24 , position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8476460.jpg")
leon= Player.create!(name: "Leon Draisaitl", age: 21 , position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8477934.jpg")
vladimir= Player.create!(name: "Vladimir Tarasenko", age: 25 , position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8475765.jpg")
artemi= Player.create!(name: "Artemi Panarin", age:25 , position:"Forward", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8478550.jpg")
brent= Player.create!(name: "Brent Burns", age: 32 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8470613.jpg")
hedman= Player.create!(name: "Victor Hedman", age: 26 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8475167.jpg")
erik= Player.create!(name: "Erik Karlsson", age: 26 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8474578.jpg")
kevin= Player.create!(name: "Kevin Shattenkirk", age: 28 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8474031.jpg")
duncan= Player.create!(name: "Duncan Keith", age: 33 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8470281.jpg")
dustin= Player.create!(name: "Dustin Byfuglien", age: 32 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8470834.jpg")
justin= Player.create!(name: "Justin Schultz", age: 26 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8474602.jpg")
torey= Player.create!(name: "Torey Krug", age: 26 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8476792.jpg")
dougie= Player.create!(name: "Dougie Hamilton", age: 23 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8476462.jpg")
roman= Player.create!(name: "Roman Josi", age: 26 , position:"Defender", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8474600.jpg")
pekka= Player.create!(name: "Pekka Rinne", age:34 , position:"Goalie", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8471469.jpg")
braden= Player.create!(name: "Braden Holtby", age: 27 , position:"Goalie", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8474651.jpg")
henrik= Player.create!(name: "Henrik Lundqvist", age: 35 , position:"Goalie", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8468685.jpg")
craig= Player.create!(name: "Craig Anderson", age: 35 , position:"Goalie", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8467950.jpg")
cam= Player.create!(name: "Cam Talbot", age: 29 , position:"Goalie", img_url:"https://nhl.bamcontent.com/images/headshots/current/168x168/8475660.jpg")

washington = Team.create(name:"Capitals", city: "Washington", img_url:"#")
